arikchakma/maily.to

- components/app-editor/index.tsx
- components/editor-preview.tsx
- components/iframe.tsx
- utils/detect-browser.ts
fixes #15 
iframe [onLoad](https://stackoverflow.com/questions/12076494/onload-in-iframes-not-working-if-iframe-have-non-html-document-in-src-pdf-or-t/12190776#12190776) isn't working
- set inner html in useeffect hook
> fix: blank iframe issue

- apps/web/actions/email.ts
- packages/core/package.json
- packages/core/src/editor/components/editor-bubble-menu.tsx
- packages/core/src/editor/components/image-bubble-menu.tsx
- packages/core/src/editor/extensions/button-extension.ts
- packages/core/src/editor/extensions/index.ts
- packages/core/src/editor/extensions/slash-command.tsx
- packages/core/src/editor/extensions/variable-extension.ts
- packages/core/src/editor/index.tsx
- packages/core/src/editor/nodes/button.tsx
- packages/core/src/editor/nodes/variable.tsx
- packages/render/package.json
- packages/render/src/index.ts
- packages/render/src/maily.tsx
- packages/render/src/render-async.ts
- packages/render/src/render.test.ts
- packages/render/src/render.ts
- pnpm-lock.yaml
> Implement Variable Formatter & Fallback

- packages/core/package.json
- packages/core/src/editor/extensions/index.ts
- packages/core/src/editor/index.tsx
- packages/core/src/editor/nodes/variable.tsx
- packages/core/src/editor/provider.tsx
- packages/render/package.json
- packages/render/src/maily.tsx
> feat: extend variable API

- packages/core/package.json
- packages/core/src/editor/extensions/index.ts
- packages/core/src/editor/extensions/slash-command.tsx
- packages/core/src/editor/index.tsx
- packages/core/src/editor/provider.tsx
> feat: implement slash command extend

- apps/web/components/ui/form.tsx
- package.json
- packages/core/package.json
- packages/core/src/editor/components/image-bubble-menu.tsx
- packages/core/src/editor/extensions/image-resize.tsx
- packages/render/package.json
- packages/render/src/maily.tsx
- pnpm-lock.yaml
> feat: implement image external link

- packages/core/src/editor/components/base-button.tsx
- packages/core/src/editor/components/bubble-menu-button.tsx
- packages/core/src/editor/components/column-menu/columns-bubble-menu.tsx
- packages/core/src/editor/components/column-menu/columns-width.tsx
- packages/core/src/editor/components/column-menu/use-columns-state.tsx
- packages/core/src/editor/components/editor-menu-bar.tsx
- packages/core/src/editor/components/icons/grid-lines.tsx
- packages/core/src/editor/components/image-menu/image-bubble-menu.tsx
- packages/core/src/editor/components/image-menu/image-size.tsx
- packages/core/src/editor/components/image-menu/use-image-state.tsx
- packages/core/src/editor/components/popover.tsx
- packages/core/src/editor/components/section-menu/section-bubble-menu.tsx
- packages/core/src/editor/components/section-menu/use-section-state.tsx
- packages/core/src/editor/components/spacer-bubble-menu.tsx
- packages/core/src/editor/components/text-menu/text-bubble-menu.tsx
- packages/core/src/editor/components/ui/divider.tsx
- packages/core/src/editor/components/ui/edge-spacing-controls.tsx
- packages/core/src/editor/components/ui/number-input.tsx
- packages/core/src/editor/extensions/columns/column.ts
- packages/core/src/editor/extensions/columns/columns.ts
- packages/core/src/editor/extensions/image-resize.tsx
- packages/core/src/editor/extensions/link-card.ts
- packages/core/src/editor/extensions/section/section.ts
- packages/core/src/editor/index.tsx
- packages/core/src/editor/provider.tsx
- packages/core/src/editor/utils/columns.ts
- packages/core/src/styles/index.css
- packages/render/src/maily.tsx
- Section border size and color
- Section Margin
- Section Horizontal alignment
- Column Controls
- Image size (width and height)
- Section improvements
- Columns Improvements
> feat: section improvements & image size

- packages/core/src/editor/components/column-menu/columns-width.tsx
> fix: Do not uppercase column attributes

- packages/core/src/editor/nodes/image/image-view.tsx
- packages/render/src/maily.tsx
> fix: image dimensions for Apple Mail

- packages/core/src/editor/components/column-menu/columns-bubble-menu-content.tsx
- packages/core/src/editor/components/column-menu/columns-width-config.tsx
- packages/core/src/editor/components/section-menu/section-bubble-menu.tsx
- packages/core/src/editor/components/show-popover.tsx
- packages/core/src/editor/components/ui/dropdown-menu.tsx
- packages/core/src/editor/components/ui/input-autocomplete.tsx
- packages/core/src/editor/components/ui/link-input-popover.tsx
- packages/core/src/editor/components/ui/select.tsx
- packages/core/src/editor/nodes/variable/variable-suggestions.tsx
- packages/core/src/styles/index.css
> feat: add `https://` prefix

- packages/core/src/editor/components/alignment-switch.tsx
- packages/core/src/editor/components/base-button.tsx
- packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
- packages/core/src/editor/components/section-menu/section-bubble-menu.tsx
- packages/core/src/editor/components/show-popover.tsx
- packages/core/src/editor/components/ui/select.tsx
- packages/core/src/editor/extensions/index.ts
- packages/core/src/editor/nodes/columns/column.ts
- packages/core/src/editor/nodes/columns/columns.ts
- packages/core/src/editor/nodes/for/for-view.tsx
- packages/core/src/editor/utils/is-custom-node-selected.ts
> fix: bubble menu

- packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
- packages/core/src/editor/components/image-menu/image-bubble-menu.tsx
- packages/core/src/editor/components/image-menu/use-image-state.tsx
- packages/core/src/editor/components/show-popover.tsx
- packages/core/src/editor/components/text-menu/text-bubble-menu.tsx
- packages/core/src/editor/components/text-menu/use-text-menu-state.tsx
- packages/core/src/editor/components/ui/input-autocomplete.tsx
- packages/core/src/editor/components/ui/link-input-popover.tsx
- packages/core/src/editor/extensions/index.ts
- packages/core/src/editor/nodes/button/button-label-input.tsx
- packages/core/src/editor/nodes/button/button-view.tsx
- packages/core/src/editor/nodes/button/button.tsx
- packages/core/src/editor/nodes/image/image-view.tsx
- packages/core/src/editor/nodes/image/image.ts
- packages/core/src/editor/nodes/link.ts
- packages/core/src/editor/nodes/logo/logo-view.tsx
- packages/core/src/editor/nodes/logo/logo.ts
- packages/core/src/editor/nodes/variable/variable-suggestions.tsx
- packages/core/src/editor/nodes/variable/variable-view.tsx
- packages/core/src/editor/nodes/variable/variable.ts
- packages/render/src/maily.tsx
| Block               | Attribute       | Static Text | Variables |
|---------------|-----------------|-------------|-----------|
| Button              | label           | ✅           | ✅         |
| Button              | external link   | ✅           | ✅         |
| Image & Logo  | source link     | ✅           | ✅         |
| Image & Logo  | external link   | ✅           | ✅         |
| For                    | each            | ❌           | ✅         |
|                          | Show If         | ❌           | ✅         |
| Normal Link     | href | ✅ | ✅ |
> feat: add variable in links and button label

- packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
- packages/core/src/editor/components/show-popover.tsx
- packages/core/src/editor/components/ui/input-autocomplete.tsx
- packages/core/src/editor/components/ui/link-input-popover.tsx
- packages/core/src/editor/nodes/button/button-label-input.tsx
- packages/core/src/editor/nodes/variable/variable-popover.tsx
- packages/core/src/editor/nodes/variable/variable-suggestions.tsx
It should be reviewed after #92 and update the popover for button label.
> fix: suggestion popover

- package.json
- packages/core/src/editor/components/popover.tsx
- packages/core/src/editor/components/ui/tooltip.tsx
- pnpm-lock.yaml
- turbo.json
I ran the commands in the README to start development. 
This updated various packages (I think because some aspects of package.json are defined as `latest`). 
Getting `pnpm dev` to run cleanly after that required small typescript correctness and an update to match turbo v2 syntax.
> Update packages, fix resulting build and typescript errors.

- packages/core/readme.md
- readme.md
Thank you Novu 💌
https://github.com/user-attachments/assets/d2fdaf14-2211-4946-ab67-a4ce547aabc0
https://github.com/user-attachments/assets/5e2b9ef1-5ded-4863-995d-62c7e40f946a
> sponsor: add novu

- packages/core/src/extensions.ts
exposing html extension so we can extends the methods
> feat: expose html extension

- packages/core/src/editor/components/text-menu/text-bubble-content.tsx
- packages/core/src/editor/components/ui/link-input-popover.tsx
- packages/core/src/editor/provider.tsx
> fix: remove link protocol

- apps/web/components/template-sidebar.tsx
- packages/core/src/editor/components/image-menu/image-bubble-menu.tsx
- packages/core/src/editor/components/image-menu/lock-aspect-ratio-button.tsx
- packages/core/src/editor/components/image-menu/use-image-state.tsx
- packages/core/src/editor/nodes/image/image-view.tsx
- packages/core/src/editor/nodes/image/image.ts
- packages/core/src/editor/utils/aspect-ratio.ts
This PR adds support for locking image aspect ratio, closes #153
**Video:**
https://github.com/user-attachments/assets/366b3b9c-65ed-4964-a305-5e0d556d3674
> feat: support locking image aspect ratio

- packages/core/package.json
Fix missing types issue raised by TS.
> fix: Add type exports to Maily Core

- packages/render/src/maily.tsx
- packages/render/src/render.test.ts
Minor type fix allowing tests to pass
> fix(render): tests - theme config types

- packages/core/src/editor/extensions/slash-command/slash-command-item.tsx
- packages/core/src/editor/extensions/slash-command/slash-command-view.tsx
Before:
https://github.com/user-attachments/assets/b1251a07-77aa-47f6-9353-85f3261d5083
After:
https://github.com/user-attachments/assets/094189d2-dae0-4a2b-a77c-75c877bc1eec
> fix(core): slash menu preview overlapping

- packages/core/src/editor/components/alignment-switch.tsx
https://github.com/user-attachments/assets/ee85d80f-c6bb-4cf6-a210-944d2e002886
> fix(core): undefined alignment fallback

- packages/core/src/editor/components/image-menu/image-bubble-menu.tsx
- packages/core/src/editor/nodes/image/image-view.tsx
- packages/render/src/maily.tsx
Before:
https://github.com/user-attachments/assets/719f47a1-ddff-4ef1-b97c-fe608b129060
After:
https://github.com/user-attachments/assets/9decfd71-a46c-4dec-ba32-499e0c47524b
> fix(core): unlocked aspect ratio

- packages/core/src/editor/extensions/slash-command/slash-command-search.tsx
- packages/core/src/editor/extensions/slash-command/slash-command-view.tsx
- added support for nested search in slash commands
- isolated and refactored the search logic a bit
https://github.com/user-attachments/assets/ec576d64-a010-4f47-9d82-1cc8aed5b4ec
> feat(core): allow slash cmd nested search

- packages/render/src/maily.tsx
> fix: bullet and order list margin

- packages/core/readme.md
- packages/core/src/editor/nodes/variable/variable-suggestions.tsx
- packages/core/src/editor/nodes/variable/variable-view.tsx
- packages/core/src/editor/nodes/variable/variable.ts
> feat: implement hide variable default input
